spring:
  application:
    name: city-weather
  profiles:
    active: local
task:
  update-weather:
    cron: "0 0 0 * * ?" # Once a day at midnight
api:
  key: 176a559ee67c2eee21883f021d6e13a1
  weather-url: https://api.openweathermap.org/data/2.5/weather
  units: metric
  cities-url: https://bulk.openweathermap.org/sample/city.list.min.json.gz
  city-names:
    - "Tallinn"
    - "Moscow"
    - "London"
    - "New York"
    - "Paris"
    - "Los Angeles"
    - "Berlin"
    - "Sydney"
    - "Tokyo"
    - "Beijing"
    - "Dubai"
    - "Mexico City"
    - "Seoul"
    - "Singapore"
    - "Rome"
    - "Madrid"
    - "Istanbul"
    - "Bangkok"
    - "Mumbai"
    - "Stockholm"